### ISSUE TITLE
What to buy

### ISSUE THREAD

**Issue by themoddedcube** [Tommrodrigues/homebridge-web-sprinkler#3]
Hi I am still new to homebridge and have no idea what to buy for this project or how to connect them to each other, if anyone could help me that would be awesome!

**Comment by phenotypic** [comment]
Hi there, for linking this plugin to homebridge, please refer to the 'Installation' and 'Configuration' sections of the `README.md`.

I can't offer much guidance on the specific implementation for your setup, but please refer to the `examples` folder for general guidance on implementation with an ESP8266 controller.

**Comment by themoddedcube** [comment]
Thank you so much for your help, my sprinklers have 8 zones, so where could I get a controller for that?
