### ISSUE TITLE
Follow up on Parts and Wiring 

### ISSUE THREAD

**Issue by themoddedcube** [Tommrodrigues/homebridge-web-sprinkler#5]
Hi sorry for bothering on Christmas Day, I hope you don’t mind. So the reason I am ordering from amazon instead of Ali Express is because I have Amazon gift cards I want to use and this is a good use for them, so my final parts and this board, [https://www.amazon.com/gp/product/B07HF44GBT/ref=ox_sc_act_title_2?smid=A2K4DGCC72N9AG&psc=1](url), this relay, [https://www.amazon.com/gp/product/B07C8LSXKC/ref=ox_sc_act_title_1?smid=A2NHKNRXF8LPRC&psc=1](url), and these wires to connect to my sprinkler system, [https://www.amazon.com/gp/product/B01EV70C78/ref=ox_sc_act_title_3?smid=A2WWHQ25ENKVJ1&psc=1](url). So if all my parts look okay is there any tutorial you could point me to, so I could see how to link my sprinklers?

**Comment by phenotypic** [comment]
Hello, please refrain from opening new issues each time regarding the same question, just comment on original issue.

I can't vouch for the specific parts you've linked to work, especially the relay board as it looks to be 5V. You should really do your own research, and set out a detailed plan of how you're going to implement this including the wiring before you buy anything. Have a look around on Google and YouTube if you're totally unfamiliar with relays and ESP8266 programming.

As I said though, I can't offer much more guidance what I've already said. Unfortunately, I have no incentive/time to write as detailed a guide from the ground up as it seems like you need. Please just read around carefully and make sure you grasp the key ideas before committing to anything.

**Comment by themoddedcube** [comment]
Thank you so much for all the help you have provided

When you say that the relay board is 5V what is the difference between a 3.3V board and a 5V board, will using the 5V board short circuit my sprinklers?

**Comment by phenotypic** [comment]
The board you linked will not work with the ESP8266 as it is the wrong voltage.

**Comment by themoddedcube** [comment]
So my only option for a relay board is 3.3V?

**Comment by themoddedcube** [comment]
My sprinkler system has an output of 12VAC, so what do I need to buy for that?

**Comment by themoddedcube** [comment]
My sprinklers are not smart right now and cannot connect to WiFi, so this project will make them smart?
