### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by Magicot1** [Tommrodrigues/homebridge-web-sprinkler#6]
Hello and happy new year (or almost).
I am trying to use an 8 channel relay to control some sprinklers through HomeKit, for that I bought an ESP32, I know this project is for ESP8266 but, is it posible to use it in an ESP32 or do you know any other project that I could use?

Thanks in advance.

**Comment by phenotypic** [comment]
Hi there, an ESP32 will work fine with the plug-in itself. The plug-in is not designed exclusively for ESP8266, it will in fact work with any device capable of providing a compatible API as per the `README.md`.

However, the script supplied in the `examples` folder is indeed written for an ESP8266, so you'd have to code your own sprinkler controller for the ESP32, though this shouldn't be too hard.

**Comment by Magicot1** [comment]
okey, thanks for the fast answer.
I'm new to programming so I don't know a lot about this, but I'll try to code it.
if you have any advice I'll gladly hear it

**Comment by phenotypic** [comment]
I can't offer much guidance as I haven't programmed for an ESP32 before.

Take a look at the script in the `examples` folder for reference, I can't imagine you'll have to change too much in terms of functionality.

All the hard work is really handled by the plug-in, the ESP32 will just have to do whatever is specified for the API in the `README`. Pretty much turning the correct relay on/off when requested.
