### ISSUE TITLE
Working with LinkTap

### ISSUE THREAD

**Issue by beeper99** [Tommrodrigues/homebridge-web-sprinkler#7]
Hi, I wondered if there is anyway not get this working with LinkTap?

The API is here:
https://www.link-tap.com/#!/api-for-developers

**Comment by phenotypic** [comment]
Hi there, I'm sure this plugin could be adapted to work with your device.

Unfortunately, though, I don't currently have the time or incentive to code this in myself. Please feel free to fork the plugin and make the changes yourself!
