### ISSUE TITLE
Picutre

### ISSUE THREAD

**Issue by erokoder** [Tommrodrigues/homebridge-web-sprinkler#9]
Could you provide picture of HOMEAPP.

Do you have homeKit sprinkler timer functionality with this plugin like this picture ?

![images](https://user-images.githubusercontent.com/29672138/124135475-1fdc4680-da84-11eb-9651-530f7e1cc3a0.jpg)

**Comment by phenotypic** [comment]
Hi there, unfortunately this plugin does not currently display the sprinkler timer when activated.

While the scheduling and adaptive watering in the plugin does time individual zones before activating/deactivating them, that is not currently displayed to the user - this is something I wish to add in the future, as shown in the `To-do` section.

The rest of the plugin UI is the same as the picture you have supplied - you are able to view multiple zones at once and update their states manually if you wish.
